language: node_js
node_js:
    - '0.10'
notifications:
    irc: "irc.freenode.org#generator-travis-ci"
branches:
    only:
        - master
env:
    global:
        - secure: "DgB+FXHoEYKSrgtDusF9AdL6axc1O6Yu26RxPUY65IAXPuz68H/G3uwnE2mI31XnBkf8wuVBR39vNq9G79kCnXtcwKfYpiMG6ldeokgtsK7Ox3JLscWUrR/5XGUPKElxOysD1JgJu2MJHe5SmVPTBYb5UZo1YvkRAztU5++vZSw="
        - secure: "QsRsFEIP7IGJDSLeSFDsJp+sO4xXZv7mJXsEDr31Iso82qSZMjH538m6/IUNK8kjPG82xh/cmW4TtsQnAv1EwZHC9ls9FQYJTyCkmheVpSmZqd7FcLbLhfTI6tIcW6UNqEUsvQ+GAIZRgNKHqCdeWD2ah0ONWoe3V+ATqHuxBr8="
        - GH_OWNER: mysterycommand
        - GH_PROJECT_NAME: writebloodyapp
before_script:
    - gem update --system
    - gem install sass
    - npm install -g grunt-cli bower
script:
    - bower install
    - grunt
after_success:
    - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
    - git clone https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site/
    - cd site/
    - git checkout --orphan heroku
    - git rm -rf .
    - cp -R ../dist/* .
    - cp ../dist/.* .
    - git add .
    - git commit -am "Travis build ${TRAVIS_BUILD_NUMBER}."
    - heroku git:remote -a ${GH_PROJECT_NAME}
    - heroku keys:clear
    - yes | heroku keys:add
    - yes | git push heroku heroku:master
