language: node_js
node_js:
- '0.10'
notifications:
  irc: irc.freenode.org#generator-travis-ci
branches:
  only:
  - master
  - heroku
env:
  global:
  - secure: QsRsFEIP7IGJDSLeSFDsJp+sO4xXZv7mJXsEDr31Iso82qSZMjH538m6/IUNK8kjPG82xh/cmW4TtsQnAv1EwZHC9ls9FQYJTyCkmheVpSmZqd7FcLbLhfTI6tIcW6UNqEUsvQ+GAIZRgNKHqCdeWD2ah0ONWoe3V+ATqHuxBr8=
  - GH_OWNER: mysterycommand
  - GH_PROJECT_NAME: writebloodyapp
before_script:
- travis/before_script.sh
script:
- travis/script.sh
after_success:
- travis/after_success.sh
deploy:
  provider: heroku
  api_key:
    secure: AkeBchwVsbKovfIZwKclGwdAKTpd+xch8oPTONtDxc6klV+dIcS/eDmC2VTX/wZwU7tP+NMAxReKDbJrn9K+n3Z7/nqa/rWG6721fk3lhh74F187bmOJ0/uMMjC2Mt9OWWVDhylUSfGHtPXMUPPPMQLItMtC2k9R8iu9XrvBOWs=
  app:
    heroku: writebloodyapp
